/**
 * Created by joseph on 6/16/17.
 *
 *
 Even Fibonacci numbers

 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.

 */
public class Problem2 {
    public static void main(String[] args) {
        int upperLim = 4000000;
        int sum = 0;
        int a = 1;
        int b = 1;
        int c = 2;

        while(c < upperLim){
            sum += c;
            a = c + b;
            b = c + a;
            c = a + b;
        }

        System.out.println("Total: " + sum);
    }
}
